field: 5869df8b-c9a4-47cb-b94b-1cfec6b8130f # Banner Call To Action
fieldLayouts:
  3fa1e1c6-3d95-45d4-8ed7-ecfe2eea7bb5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9fc7ddbf-1b47-46e4-a1a4-d0038b2358fe # Label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f075c801-b763-4c45-8a8b-f1b27a1c4759
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: da3d37a9-015d-4139-851e-165cffbcf443 # Url
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 95484e2e-b499-4f03-9505-e31d4bf6abbf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 91482cdd-d8e7-4688-9fa8-c7eeb53fd614
        userCondition: null
fields:
  9fc7ddbf-1b47-46e4-a1a4-d0038b2358fe: # Label
    columnSuffix: rdwzruqr
    contentColumnType: string(120)
    fieldGroup: null
    handle: label
    instructions: null
    name: Label
    searchable: false
    settings:
      byteLimit: null
      charLimit: 30
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  da3d37a9-015d-4139-851e-165cffbcf443: # Url
    columnSuffix: qwmxebat
    contentColumnType: string(255)
    fieldGroup: null
    handle: callToActionUrl
    instructions: 'Please fill in a complete URL (e.g. https://place-you-want/to/link/to.com)'
    name: Url
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: callToAction
name: 'Call To Action'
sortOrder: 1
