field: f3455c98-6520-43ce-a2ac-1683fd9f14cf # Features
fieldLayouts:
  30fffa31-b33f-46c8-ad09-9ac092815abf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 74429bd1-36e8-4881-8621-1573ea3e3fdc # Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37b70dbc-1974-4ed7-a84b-6af09b9dacd3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4777e61a-d332-4b9c-96e2-e4c0a35af076 # Description
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a070dbe-80d1-427d-b7f9-3365014e92f1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 05eb0cdd-f42b-4ba7-927f-12cb6c1b93de # Icon
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9073ea9a-c77d-4a15-aef5-3d7de15eb8fa
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 53fe5eaa-5300-4b30-a06e-810c47364b52
        userCondition: null
fields:
  05eb0cdd-f42b-4ba7-927f-12cb6c1b93de: # Icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: featureIcon
    instructions: null
    name: Icon
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:a9f8cd7f-5cfe-4c94-8055-9fdd73c3c08f' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a9f8cd7f-5cfe-4c94-8055-9fdd73c3c08f' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources:
        - 'volume:a9f8cd7f-5cfe-4c94-8055-9fdd73c3c08f' # Uploads
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  4777e61a-d332-4b9c-96e2-e4c0a35af076: # Description
    columnSuffix: aewpqryt
    contentColumnType: text
    fieldGroup: null
    handle: featureDescription
    instructions: null
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 2
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  74429bd1-36e8-4881-8621-1573ea3e3fdc: # Title
    columnSuffix: itarwrkl
    contentColumnType: text
    fieldGroup: null
    handle: featureTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: feature
name: Feature
sortOrder: 1
