field: b7acd107-9e81-4b5d-a429-ab01a2f2f077 # Menu
fieldLayouts:
  df8af336-3b0c-4919-a23d-8e0608a413ef:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7b4823ed-36d1-4b74-a926-b3e803de5a45 # Label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26a0e4d3-ea17-4c50-bdd0-c47c1f5dc3b0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0157bddf-9fa1-4116-95d0-dcf4ef8476bf # Entry
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a709f326-be87-4371-82b4-21d1a734a277
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4af11605-e6c6-413c-aef1-495f044b8e07
        userCondition: null
fields:
  7b4823ed-36d1-4b74-a926-b3e803de5a45: # Label
    columnSuffix: hvrwzkbf
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: null
    name: Label
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  0157bddf-9fa1-4116-95d0-dcf4ef8476bf: # Entry
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: entry
    instructions: null
    name: Entry
    searchable: false
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: true
      source: null
      sources:
        - 'section:6eece8c8-71a4-4945-83f3-b8992cf3bdbf' # Dossiers
        - singles
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: menuItems
name: 'Menu Items'
sortOrder: 1
