field: f27169dd-394b-43f3-a168-a31798fdb956 # Researchdossier Sources
fieldLayouts:
  1186b23f-fc21-4511-a4ee-0e161065aeb5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6ef40c2a-25f5-4a7a-b123-aaace31e001b # Source Name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47af9915-9a6c-4041-91b4-abfced7acee7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dca4d31f-f810-4d55-b207-01e53a055a21 # Source Link
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff6d075e-3577-425f-8abf-687bdd0e0e8d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e4de7865-d975-4cb2-80dd-864a4e2dd770
        userCondition: null
fields:
  6ef40c2a-25f5-4a7a-b123-aaace31e001b: # Source Name
    columnSuffix: iebohxrx
    contentColumnType: text
    fieldGroup: null
    handle: sourceName
    instructions: null
    name: 'Source Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  dca4d31f-f810-4d55-b207-01e53a055a21: # Source Link
    columnSuffix: lchgxhik
    contentColumnType: string(255)
    fieldGroup: null
    handle: sourceLink
    instructions: null
    name: 'Source Link'
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: sources
name: Sources
sortOrder: 1
