fieldLayouts:
  3a0f9c8f-8ddd-4e43-98ee-8bfff816230b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 806bdba3-10c7-431e-b626-56211a5af0fb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 45939e60-2be6-4e7a-b522-6c26d130ac4c
        userCondition: null
handle: resetPassword
hasTitleField: false
name: 'Reset Password'
section: 4b59c426-8e44-4212-90b5-c323a9cdc382 # Reset Password
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
