fieldLayouts:
  70d11bec-542e-4117-a173-56f5b9a48694:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c4c4d992-ceac-416c-b45d-994daf0f4f53
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d88c8912-47da-4a18-bdba-3bf2b425c4b4
        userCondition: null
handle: setPassword
hasTitleField: false
name: 'Set Password'
section: 3c7f3529-7f31-4cad-ad38-81a487acec33 # Set Password
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
