defaultPlacement: beginning
fieldLayouts:
  7da9c693-923e-48a3-aaa8-27937fc3dbd6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 8bc26e96-5e83-46a4-b9a2-b8e9918ceeb7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 85a50ef0-e635-4d2f-a22e-070a8b1a503c # Theme Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47d049b5-c5ea-4e7c-a015-a8090d11906c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0ba405d6-2ee8-4a46-a191-5d1979456052
        userCondition: null
handle: themes
name: Themes
siteSettings:
  1cc07613-bcbe-41a4-a746-e98bc2d3fd9a: # ArabTeach
    hasUrls: true
    template: themes/_entry
    uriFormat: 'themes/{slug}'
structure:
  maxLevels: 1
  uid: a21e1372-3f12-4a76-b836-bb27b06d48ca
