columnSuffix: takawwyh
contentColumnType: text
fieldGroup: 02105aa0-8215-4edd-b3ff-7127c0165675 # Dossiers
handle: articleExcerpt
instructions: null
name: 'Article Excerpt'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
