columnSuffix: null
contentColumnType: string
fieldGroup: 9461779e-6e19-4a60-aa1d-3471bf2a5ed8 # Homepage
handle: bannerCallToAction
instructions: null
name: 'Banner Call To Action'
searchable: false
settings:
  contentTable: '{{%matrixcontent_bannercalltoaction}}'
  maxBlocks: 1
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
