columnSuffix: null
contentColumnType: string
fieldGroup: ff43ce60-87a7-4b19-ac73-c3577a93e70e # Researchdossiers
handle: researchdossierSources
instructions: 'A place to add al the sources you used. '
name: 'Researchdossier Sources'
searchable: false
settings:
  contentTable: '{{%matrixcontent_researchdossiersources}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
