fieldLayouts:
  e4cdc075-b727-48dd-af65-c82135b093e6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7b24337d-9cd1-4526-b8ee-a05bbbee17e8 # disclaimer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f0b1cbd0-ae24-442a-a6f3-69a0d56815dc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 18e0807a-c721-414f-b97a-7196e2d93fda
        userCondition: null
handle: footer
name: Footer
sortOrder: 1
