description: ''
handle: administrators
name: Administrators
permissions:
  - accesscp
  - accesscpwhensystemisoff
  - accesssitewhensystemisoff
  - administrateusers
  - 'assignusergroup:9524199c-510f-4a96-871c-20643545a6f4' # Administrators
  - assignuserpermissions
  - 'createentries:6eece8c8-71a4-4945-83f3-b8992cf3bdbf' # Dossiers
  - 'createfolders:a9f8cd7f-5cfe-4c94-8055-9fdd73c3c08f' # Uploads
  - 'deleteassets:a9f8cd7f-5cfe-4c94-8055-9fdd73c3c08f' # Uploads
  - 'deletecategories:aa37cc9c-6e1f-4bc4-96f8-4de66f06ac3f' # Themes
  - 'deleteentries:6eece8c8-71a4-4945-83f3-b8992cf3bdbf' # Dossiers
  - 'deletepeerassets:a9f8cd7f-5cfe-4c94-8055-9fdd73c3c08f' # Uploads
  - 'deletepeerentries:6eece8c8-71a4-4945-83f3-b8992cf3bdbf' # Dossiers
  - 'deletepeerentrydrafts:607f48b6-ad44-48b9-8958-e669915f6b28' # Dashboard
  - 'deletepeerentrydrafts:6eece8c8-71a4-4945-83f3-b8992cf3bdbf' # Dossiers
  - 'deletepeerentrydrafts:931f3411-3c8e-4d4e-bec1-544a33289596' # Home
  - deleteusers
  - 'editglobalset:cbe1981c-ede1-4447-9902-d958bacbfea7' # Footer
  - 'editimages:a9f8cd7f-5cfe-4c94-8055-9fdd73c3c08f' # Uploads
  - 'editpeerimages:a9f8cd7f-5cfe-4c94-8055-9fdd73c3c08f' # Uploads
  - editusers
  - impersonateusers
  - moderateusers
  - performupdates
  - registerusers
  - 'replacefiles:a9f8cd7f-5cfe-4c94-8055-9fdd73c3c08f' # Uploads
  - 'replacepeerfiles:a9f8cd7f-5cfe-4c94-8055-9fdd73c3c08f' # Uploads
  - 'saveassets:a9f8cd7f-5cfe-4c94-8055-9fdd73c3c08f' # Uploads
  - 'savecategories:aa37cc9c-6e1f-4bc4-96f8-4de66f06ac3f' # Themes
  - 'saveentries:607f48b6-ad44-48b9-8958-e669915f6b28' # Dashboard
  - 'saveentries:6eece8c8-71a4-4945-83f3-b8992cf3bdbf' # Dossiers
  - 'saveentries:931f3411-3c8e-4d4e-bec1-544a33289596' # Home
  - 'savepeerassets:a9f8cd7f-5cfe-4c94-8055-9fdd73c3c08f' # Uploads
  - 'savepeercategorydrafts:aa37cc9c-6e1f-4bc4-96f8-4de66f06ac3f' # Themes
  - 'savepeerentries:6eece8c8-71a4-4945-83f3-b8992cf3bdbf' # Dossiers
  - 'savepeerentrydrafts:607f48b6-ad44-48b9-8958-e669915f6b28' # Dashboard
  - 'savepeerentrydrafts:6eece8c8-71a4-4945-83f3-b8992cf3bdbf' # Dossiers
  - 'savepeerentrydrafts:931f3411-3c8e-4d4e-bec1-544a33289596' # Home
  - 'viewassets:a9f8cd7f-5cfe-4c94-8055-9fdd73c3c08f' # Uploads
  - 'viewcategories:aa37cc9c-6e1f-4bc4-96f8-4de66f06ac3f' # Themes
  - 'viewentries:607f48b6-ad44-48b9-8958-e669915f6b28' # Dashboard
  - 'viewentries:6eece8c8-71a4-4945-83f3-b8992cf3bdbf' # Dossiers
  - 'viewentries:931f3411-3c8e-4d4e-bec1-544a33289596' # Home
  - 'viewpeerassets:a9f8cd7f-5cfe-4c94-8055-9fdd73c3c08f' # Uploads
  - 'viewpeercategorydrafts:aa37cc9c-6e1f-4bc4-96f8-4de66f06ac3f' # Themes
  - 'viewpeerentries:6eece8c8-71a4-4945-83f3-b8992cf3bdbf' # Dossiers
  - 'viewpeerentrydrafts:607f48b6-ad44-48b9-8958-e669915f6b28' # Dashboard
  - 'viewpeerentrydrafts:6eece8c8-71a4-4945-83f3-b8992cf3bdbf' # Dossiers
  - 'viewpeerentrydrafts:931f3411-3c8e-4d4e-bec1-544a33289596' # Home
