defaultPlacement: end
enableVersioning: true
handle: escaperooms
name: Escaperooms
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  1cc07613-bcbe-41a4-a746-e98bc2d3fd9a: # ArabTeach
    enabledByDefault: true
    hasUrls: true
    template: escaperooms/_entry
    uriFormat: 'escaperooms/{slug}'
type: channel
